name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          pwd
          echo "Files in current directory:"
          ls -la
          echo "Checking if my-react-app-superman exists:"
          ls -la my-react-app-superman || echo "Directory not found"

      - name: Navigate to correct directory
        run: |
          if [ -d "my-react-app-superman" ]; then
            cd my-react-app-superman
            echo "Moved to my-react-app-superman directory"
            ls -la
          else
            echo "Using current directory"
            ls -la
          fi
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -d "my-react-app-superman" ]; then
            cd my-react-app-superman
            npm install
          else
            npm install
          fi

      - name: Build
        run: |
          if [ -d "my-react-app-superman" ]; then
            cd my-react-app-superman
            CI=false npm run build
          else
            CI=false npm run build
          fi
        env:
          REACT_APP_API_URL: 'https://pimfeederplus-git-main-krystlizes-projects.vercel.app'
          REACT_APP_API_BASE_URL: 'https://pimfeederplus-git-main-krystlizes-projects.vercel.app/api'
          REACT_APP_ENV: 'production'

      - name: Determine build path
        id: build-path
        run: |
          if [ -d "my-react-app-superman/build" ]; then
            echo "path=my-react-app-superman/build" >> $GITHUB_OUTPUT
          elif [ -d "build" ]; then
            echo "path=build" >> $GITHUB_OUTPUT
          else
            echo "No build directory found"
            exit 1
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ steps.build-path.outputs.path }} 