name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "." # Changed from "my-react-app-superman" to "." to point to root directory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Debug before setup
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Content of public directory (if exists):"
          ls -la public || echo "Public directory not found"

      - name: Ensure public directory exists
        run: |
          mkdir -p public
          cp -r public/* public/ || echo "No files to copy"
          echo "Content of public directory after setup:"
          ls -la public/

      - name: Install dependencies
        working-directory: ${{ env.BUILD_PATH }}
        run: npm ci

      - name: Build
        working-directory: ${{ env.BUILD_PATH }}
        env:
          CI: false # Disable treating warnings as errors
          REACT_APP_API_URL: 'https://pimfeederplus-git-main-krystlizes-projects.vercel.app'
          REACT_APP_API_BASE_URL: 'https://pimfeederplus-git-main-krystlizes-projects.vercel.app/api'
          REACT_APP_ENV: 'production'
        run: |
          npm run build
          ls -la build || echo "Build directory not found"

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Build path contents:"
          ls -la ${{ env.BUILD_PATH }}
          echo "Build directory contents (if exists):"
          ls -la ${{ env.BUILD_PATH }}/build || echo "Build directory not found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 